import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import Layout from '@/components/Layout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';
import { verificationApi, type PendingVerification } from '@/lib/api';
import {
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  FlaskConical,
  TrendingUp,
  Activity,
  Lightbulb,
  Download,
  Mail,
} from 'lucide-react';

// ─── PDF Download ─────────────────────────────────────────────────────────────
const downloadPDF = (p: PendingVerification) => {
  const date = new Date(p.createdAt).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });

  const tipsHtml = p.output.soilHealthTips?.length
    ? `<h2>Soil Health Tips</h2>
       <ol>${p.output.soilHealthTips.map((t) => `<li>${t}</li>`).join('')}</ol>`
    : '';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>AgriFert Report – ${p.userId.name}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; color: #1a1a1a; background: #fff; padding: 40px; }
  h1 { color: #2d6a4f; font-size: 22px; border-bottom: 2px solid #2d6a4f; padding-bottom: 8px; margin-bottom: 16px; }
  h2 { color: #2d6a4f; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; margin: 20px 0 8px; }
  .meta { font-size: 13px; color: #555; margin-bottom: 4px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin: 10px 0; }
  .box { background: #f5f5f5; padding: 10px 14px; border-radius: 6px; }
  .label { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }
  .value { font-size: 15px; font-weight: 700; margin-top: 2px; }
  .highlight { background: #e9f5ee; border-left: 4px solid #2d6a4f; padding: 14px 16px; border-radius: 4px; margin: 10px 0; }
  .fert-name { font-size: 26px; font-weight: 800; color: #2d6a4f; }
  ol { padding-left: 18px; font-size: 13px; line-height: 1.8; color: #444; }
  footer { margin-top: 40px; font-size: 10px; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 12px; }
  @media print {
    body { padding: 20px; }
    @page { margin: 1.5cm; }
  }
</style>
</head>
<body>
<h1>🌱 AgriFert – Soil Analysis Report</h1>
<p class="meta"><strong>Farmer:</strong> ${p.userId.name} &nbsp;|&nbsp; ${p.userId.email}</p>
<p class="meta"><strong>Date:</strong> ${date}</p>

<h2>Soil Input Parameters</h2>
<div class="grid">
  <div class="box"><div class="label">Crop Type</div><div class="value">${p.input.cropType}</div></div>
  <div class="box"><div class="label">Soil Type</div><div class="value">${p.input.soilType}</div></div>
  <div class="box"><div class="label">Temperature</div><div class="value">${p.input.temperature}°C</div></div>
  <div class="box"><div class="label">Humidity</div><div class="value">${p.input.humidity}%</div></div>
  <div class="box"><div class="label">Moisture</div><div class="value">${p.input.moisture}%</div></div>
  <div class="box"><div class="label">N / P / K</div><div class="value">${p.input.nitrogen} / ${p.input.phosphorous} / ${p.input.potassium}</div></div>
</div>

<h2>Model Recommendation</h2>
<div class="highlight">
  <div class="label">Recommended Fertilizer</div>
  <div class="fert-name">${p.output.fertilizerName}</div>
  ${p.output.totalQty != null ? `<div style="margin-top:4px;font-size:13px;color:#555">Total Quantity: <strong>${p.output.totalQty} kg/acre</strong></div>` : ''}
</div>
<div class="grid">
  ${p.output.yieldImprovement != null ? `<div class="box"><div class="label">Yield Improvement</div><div class="value" style="color:#22763c">+${p.output.yieldImprovement}%</div></div>` : ''}
  ${p.output.modelConfidence != null ? `<div class="box"><div class="label">Model Confidence</div><div class="value">${(p.output.modelConfidence * 100).toFixed(1)}%</div></div>` : ''}
</div>

${tipsHtml}

<footer>Generated by AgriFert AI &nbsp;·&nbsp; ${new Date().toLocaleString('en-IN')}</footer>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  // Small delay so browser finishes rendering before triggering print
  setTimeout(() => {
    win.print();
    // Close the tab after the print dialog is dismissed
    win.addEventListener('afterprint', () => win.close());
  }, 350);
};

// ─── Single Verification Card (collapsible) ───────────────────────────────────
const VerificationCard = ({ p }: { p: PendingVerification }) => {
  const [expanded, setExpanded] = useState(false);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const maxNPK = Math.max(p.input.nitrogen, p.input.phosphorous, p.input.potassium) || 1;

  const verifyMutation = useMutation({
    mutationFn: () => verificationApi.verify(p._id),
    onSuccess: () => {
      toast({ title: 'Verified ✓', description: 'Record saved for model retraining.' });
      queryClient.invalidateQueries({ queryKey: ['admin-verifications'] });
      queryClient.invalidateQueries({ queryKey: ['admin-stats'] });
    },
    onError: () => toast({ title: 'Verification failed', variant: 'destructive' }),
  });

  return (
    <Card className="overflow-hidden transition-shadow duration-200 hover:shadow-elevated">
      {/* Accent strip */}
      <div className="h-1 w-full bg-gradient-hero" />

      {/* ── Collapsed summary row (always visible) ── */}
      <div
        className="flex cursor-pointer flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"
        onClick={() => setExpanded((e) => !e)}
        role="button"
        aria-expanded={expanded}
      >
        {/* Left: avatar + name + badges */}
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-hero text-sm font-bold text-primary-foreground">
            {p.userId.name.charAt(0).toUpperCase()}
          </div>
          <div>
            <p className="font-semibold text-foreground">{p.userId.name}</p>
            <div className="mt-0.5 flex flex-wrap items-center gap-1.5">
              <span className="text-xs text-muted-foreground capitalize">{p.input.cropType}</span>
              <span className="text-xs text-muted-foreground">·</span>
              <span className="text-xs text-muted-foreground capitalize">{p.input.soilType} soil</span>
              <span className="text-xs text-muted-foreground">·</span>
              <span className="text-xs text-muted-foreground">
                {new Date(p.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
              </span>
            </div>
          </div>
        </div>

        {/* Right: fertilizer badge + confidence + expand icon */}
        <div className="flex items-center gap-3 pl-13 sm:pl-0">
          <Badge variant="outline" className="font-medium">{p.output.fertilizerName}</Badge>
          {p.output.yieldImprovement != null && (
            <span className="text-sm font-semibold text-success">+{p.output.yieldImprovement}%</span>
          )}
          {p.output.modelConfidence != null && (
            <span className="hidden text-xs text-muted-foreground sm:block">
              {(p.output.modelConfidence * 100).toFixed(1)}% conf.
            </span>
          )}
          {expanded
            ? <ChevronUp className="h-4 w-4 shrink-0 text-muted-foreground" />
            : <ChevronDown className="h-4 w-4 shrink-0 text-muted-foreground" />}
        </div>
      </div>

      {/* ── Expanded detail section ── */}
      {expanded && (
        <>
          <Separator />
          <CardContent className="grid gap-5 pt-5 md:grid-cols-2">

            {/* Soil Inputs */}
            <div className="space-y-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Soil Input Parameters
              </p>
              <div className="grid grid-cols-3 gap-2">
                {[
                  { label: 'Crop',     value: p.input.cropType },
                  { label: 'Soil',     value: p.input.soilType },
                  { label: 'Temp',     value: `${p.input.temperature}°C` },
                  { label: 'Humidity', value: `${p.input.humidity}%` },
                  { label: 'Moisture', value: `${p.input.moisture}%` },
                  { label: 'NPK',      value: `${p.input.nitrogen}/${p.input.phosphorous}/${p.input.potassium}` },
                ].map(({ label, value }) => (
                  <div key={label} className="rounded-lg bg-muted p-2 text-center">
                    <p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p>
                    <p className="mt-0.5 text-sm font-semibold capitalize text-foreground">{value}</p>
                  </div>
                ))}
              </div>

              {/* NPK bars */}
              <div className="space-y-2 rounded-xl bg-muted/50 p-3">
                <p className="text-xs font-medium text-muted-foreground">NPK Breakdown</p>
                {[
                  { label: 'Nitrogen (N)',   val: p.input.nitrogen,    cls: '[&>div]:bg-primary' },
                  { label: 'Phosphorus (P)', val: p.input.phosphorous, cls: '[&>div]:bg-accent' },
                  { label: 'Potassium (K)',  val: p.input.potassium,   cls: '[&>div]:bg-soil' },
                ].map(({ label, val, cls }) => (
                  <div key={label}>
                    <div className="mb-1 flex justify-between text-xs">
                      <span className="text-muted-foreground">{label}</span>
                      <span className="font-medium">{val} kg/ha</span>
                    </div>
                    <Progress value={(val / maxNPK) * 100} className={`h-2 bg-muted ${cls}`} />
                  </div>
                ))}
              </div>
            </div>

            {/* Model Output */}
            <div className="space-y-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Model Recommendation
              </p>

              <div className="flex items-center gap-3 rounded-xl bg-primary/10 p-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-hero">
                  <FlaskConical className="h-5 w-5 text-primary-foreground" />
                </div>
                <div>
                  <p className="text-xs text-muted-foreground">Recommended Fertilizer</p>
                  <p className="text-xl font-bold text-foreground">{p.output.fertilizerName}</p>
                  {p.output.totalQty != null && (
                    <p className="text-xs text-muted-foreground">{p.output.totalQty} kg/acre total</p>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className="rounded-xl bg-success/10 p-3 text-center">
                  <TrendingUp className="mx-auto mb-1 h-4 w-4 text-success" />
                  <p className="text-xs text-muted-foreground">Yield Improvement</p>
                  <p className="text-lg font-bold text-success">
                    {p.output.yieldImprovement != null ? `+${p.output.yieldImprovement}%` : '—'}
                  </p>
                </div>
                <div className="rounded-xl bg-muted p-3 text-center">
                  <Activity className="mx-auto mb-1 h-4 w-4 text-primary" />
                  <p className="text-xs text-muted-foreground">Confidence</p>
                  <p className="text-lg font-bold text-foreground">
                    {p.output.modelConfidence != null
                      ? `${(p.output.modelConfidence * 100).toFixed(1)}%`
                      : '—'}
                  </p>
                </div>
              </div>

              {p.output.modelConfidence != null && (
                <div className="rounded-xl bg-muted/50 p-3">
                  <div className="mb-1.5 flex justify-between text-xs">
                    <span className="text-muted-foreground">Model Confidence</span>
                    <span className="font-medium">{(p.output.modelConfidence * 100).toFixed(1)}%</span>
                  </div>
                  <div className="relative h-2.5 overflow-hidden rounded-full bg-muted">
                    <div
                      className="absolute left-0 top-0 h-full rounded-full bg-gradient-hero transition-all duration-700"
                      style={{ width: `${(p.output.modelConfidence * 100).toFixed(1)}%` }}
                    />
                  </div>
                </div>
              )}

              {p.output.soilHealthTips && p.output.soilHealthTips.length > 0 && (
                <div className="rounded-xl border border-border/50 p-3">
                  <div className="mb-2 flex items-center gap-1.5">
                    <Lightbulb className="h-3.5 w-3.5 text-accent-foreground" />
                    <p className="text-xs font-semibold text-muted-foreground">AI Soil Health Tips</p>
                  </div>
                  <ul className="space-y-1.5">
                    {p.output.soilHealthTips.map((tip, i) => (
                      <li key={i} className="flex gap-2 text-xs text-muted-foreground">
                        <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-primary/10 text-[10px] font-bold text-primary">
                          {i + 1}
                        </span>
                        {tip}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </CardContent>

          {/* Action row */}
          <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border/50 px-4 py-3">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Mail className="h-3.5 w-3.5" />
              {p.userId.email}
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5"
                onClick={(e) => { e.stopPropagation(); downloadPDF(p); }}
              >
                <Download className="h-3.5 w-3.5" />
                Download PDF
              </Button>
              <Button
                size="sm"
                className="gap-1.5"
                disabled={verifyMutation.isPending}
                onClick={(e) => { e.stopPropagation(); verifyMutation.mutate(); }}
              >
                <CheckCircle className="h-3.5 w-3.5" />
                {verifyMutation.isPending ? 'Saving…' : 'Mark Verified'}
              </Button>
            </div>
          </div>
        </>
      )}
    </Card>
  );
};

// ─── Skeleton ─────────────────────────────────────────────────────────────────
const PageSkeleton = () => (
  <Layout>
    <div className="container py-8 md:py-12">
      <div className="mx-auto max-w-4xl space-y-4">
        <Skeleton className="h-10 w-56" />
        {[...Array(5)].map((_, i) => <Skeleton key={i} className="h-20 w-full rounded-xl" />)}
      </div>
    </div>
  </Layout>
);

// ─── Main Page ────────────────────────────────────────────────────────────────
const LIMIT = 15;

const VerificationPage = () => {
  const navigate  = useNavigate();
  const [page, setPage] = useState(1);

  const { data, isLoading } = useQuery({
    queryKey: ['admin-verifications', page],
    queryFn: async () => {
      const res = await verificationApi.getPending(page, LIMIT);
      return res.data.data;
    },
    placeholderData: (prev) => prev,
  });

  if (isLoading && !data) return <PageSkeleton />;

  const predictions = data?.predictions ?? [];
  const pagination  = data?.pagination;

  return (
    <Layout>
      <div className="container py-8 md:py-12">
        <div className="mx-auto max-w-4xl space-y-5">

          {/* Header */}
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <button
                onClick={() => navigate('/admin')}
                className="mb-2 flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                <ArrowLeft className="h-3.5 w-3.5" />
                Back to Dashboard
              </button>
              <h1 className="text-2xl font-bold text-foreground sm:text-3xl">
                Pending Verifications
              </h1>
              <p className="mt-1 text-sm text-muted-foreground">
                Click a row to expand full details · Download PDF · Mark as verified
              </p>
            </div>
            {pagination && pagination.total > 0 && (
              <span className="shrink-0 self-start rounded-full bg-muted px-3 py-1 text-sm text-muted-foreground">
                {pagination.total} pending
              </span>
            )}
          </div>

          {/* Empty state */}
          {!isLoading && predictions.length === 0 && (
            <Card>
              <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
                <CheckCircle className="h-12 w-12 text-success" />
                <p className="text-lg font-semibold">All predictions verified!</p>
                <p className="text-sm text-muted-foreground">No pending verifications at this time.</p>
                <Button variant="outline" onClick={() => navigate('/admin')}>
                  Back to Dashboard
                </Button>
              </CardContent>
            </Card>
          )}

          {/* Cards */}
          <div className="space-y-3">
            {predictions.map((p) => (
              <VerificationCard key={p._id} p={p} />
            ))}
          </div>

          {/* Pagination */}
          {pagination && pagination.totalPages > 1 && (
            <div className="flex flex-col items-center justify-between gap-3 sm:flex-row">
              <span className="text-sm text-muted-foreground">
                Showing {(pagination.page - 1) * pagination.limit + 1}–
                {Math.min(pagination.page * pagination.limit, pagination.total)} of {pagination.total}
              </span>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" className="gap-1" disabled={pagination.page <= 1} onClick={() => setPage((p) => p - 1)}>
                  <ChevronLeft className="h-4 w-4" /> Prev
                </Button>
                <Button variant="outline" size="sm" className="gap-1" disabled={pagination.page >= pagination.totalPages} onClick={() => setPage((p) => p + 1)}>
                  Next <ChevronRight className="h-4 w-4" />
                </Button>
              </div>
            </div>
          )}

        </div>
      </div>
    </Layout>
  );
};

export default VerificationPage;
